[FIX] farmsupply_branding: Fix AttributeError in mail_notification_layout
In QWeb templates, when a field does not exist in the record of a model,
issuing record.non_existing_field_name throws an AttributeError (e.g.
'hr.employee' object has no attribute 'partner_id'), even when just
trying to use this inside a t-if attribute.

To overcome this, at the beginning of the template, a variable
record_brand_id is set by checking if any form of
res_partner.brand_id exists in the template's 'record'.

task-3750290

Additionally, removed stored=True from brand_brand.image field
since the correct field parameter is 'store'. Also, Image fields
are store=True by default.